# Cloud Build configuration básica para desplegar frontend Angular con Node.js SSR
steps:
  # Compilar la aplicación Angular con SSR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.ssr'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/parking-services-repo/parking-frontend:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/parking-services-repo/parking-frontend:latest'
      - '.'

  # Push a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/parking-services-repo/parking-frontend:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/parking-services-repo/parking-frontend:latest'

  # Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'parking-frontend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/parking-services-repo/parking-frontend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--timeout'
      - '600s'
      - '--cpu'
      - '1'
      - '--memory'
      - '1Gi'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'

# Opciones de build
options:
  machineType: 'E2_MEDIUM'
  logging: CLOUD_LOGGING_ONLY

# Timeout
timeout: '1200s'

# Imágenes a almacenar
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/parking-services-repo/parking-frontend:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/parking-services-repo/parking-frontend:latest'
